version: '3.9'

networks: 
  jenkins:
    name: jenkins  
  grid:
    name: grid
    
volumes:
  jenkins_home:
    
services:
  jenkins:
    user: root
    container_name: jenkins-master
    ports:
      - 8081:8080
      - 50001:50000
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    image: jenkins/jenkins:lts
    
  selenium-hub:    
    container_name: selenium-hub
    networks:
      - grid
    ports:
      - "4444:4444"
    image: selenium/hub:latest
    
  chrome:    
    networks:
      - grid
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-chrome-debug:latest
    
  firefox:    
    networks:
      - grid
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-firefox-debug:latest
 