version: '3.0'

networks:
  grid:
   
services:    
  selenium-hub:    
    container_name: selenium-hub
    networks:
      - grid
    ports:
      - "4444:4444"
    image: selenium/hub:latest
    
  chrome:    
    networks:
      - grid
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-chrome-debug:latest
    
  firefox:    
    networks:
      - grid
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    image: selenium/node-firefox-debug:latest
 
  selenium-test:
    networks:
      - grid
    volumes:
      - ./reports:/home/docker-jenkins-test/target
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=selenium-hub
    image: ashkumarkdocker/docker-e2e-automation
    